# Site settings
author: Samuel Middleton
title: A SQL Query Walks into a Bar
header-img: img/home-bg.png
email: samuelmiddleton93@gmail.com
copyright_name: Samuel Middleton
description: > # this means to ignore newlines until "baseurl:"
  Adventures in Learning Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: TalkDatumToMe
github_username:  emperorner0

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-modernist
